"""empty message

Revision ID: 30fb8c1bc89f
Revises: 1b5f317ee013
Create Date: 2017-09-28 16:20:37.515056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30fb8c1bc89f'
down_revision = '1b5f317ee013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlist', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketlist', 'description')
    # ### end Alembic commands ###
